#
# Kubernetes configuration for info-server as service
#

apiVersion: v1
kind: Service
metadata:
  name: info-server
  labels:
    app: info-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: info-server

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: info-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: info-server
    spec:
      containers:
      - name: info-server-container
        image: hapkecom/info-server
        ports:
        - containerPort: 8080
        env:
          # provide environment variable with pod and namespace name using Kubernetes Downward API,
          #   https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/user-guide/downward-api.md
          #   https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/user-guide/downward-api/dapi-pod.yaml
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 50Mi


